---
projectName: FHIR-training-on-platform
image: jembi/platform:2.0.0
logPath: /tmp/logs

packages:
  - fhir-training-on-platform
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir

customPackages:
  - id: fhir-training-on-platform
    path: ../fhir-training-on-platform

profiles:
  - name: local
    packages:
      - fhir-training-on-platform
    envFiles:
      - ./.env.local
    dev: true
    
  - name: local-remove-fhir
    packages:
      - fhir-datastore-hapi-fhir
    envFiles:
      - ./.env.local
    dev: true
    only: true

  - name: local-deploy-ig
    packages:
      - fhir-datastore-hapi-fhir
      - fhir-training-on-platform
    envFiles:
      - ./.env.local
    dev: true
    only: true

  - name: qa
    packages:
      - fhir-training-on-platform
      - reverse-proxy-nginx
    envFiles:
      - ./.env.qa
    dev: false

  - name: qa-remove-fhir
    packages:
      - fhir-datastore-hapi-fhir
    envFiles:
      - ./.env.qa
    dev: false
    only: true

  - name: qa-deploy-ig
    packages:
      - fhir-datastore-hapi-fhir
      - fhir-training-on-platform
    envFiles:
      - ./.env.qa
    dev: false
    only: true
