---
projectName: FHIR-training-on-platform
image: jembi/platform:2.4.0
logPath: /tmp/logs

packages:
  - fhir-training-on-platform
  - reverse-proxy-nginx
  - fhir-datastore-hapi-fhir

customPackages:
  - id: fhir-training-on-platform
    path: ../fhir-training-on-platform

profiles:
  - name: local
    packages:
      - fhir-training-on-platform
    envFiles:
      - ./.env.local
    dev: true
    
  - name: local-remove-fhir
    packages:
      - fhir-datastore-hapi-fhir
    envFiles:
      - ./.env.local
    dev: true
    only: true

  - name: local-deploy-ig
    packages:
      - fhir-datastore-hapi-fhir
      - fhir-training-on-platform
    envFiles:
      - ./.env.local
    dev: true
    only: true

  - name: qa
    packages:
      - fhir-training-on-platform
      - reverse-proxy-nginx
    envFiles:
      - ./.env.qa
    dev: false

  - name: qa-remove-fhir
    packages:
      - fhir-datastore-hapi-fhir
    envFiles:
      - ./.env.qa
    dev: false
    only: true

  - name: qa-deploy-ig
    packages:
      - fhir-datastore-hapi-fhir
      - fhir-training-on-platform
    envFiles:
      - ./.env.qa
    dev: false
    only: true

# hapi-fhir-cli upload-terminology -d "/Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/custom1/custom1.zip" -v r4 -t http://20.119.216.32:8080/fhir -u http://20.119.216.32:8080/fhir/CodeSystem/2
