---
- hosts: leader
  tasks:
    # This task is not split into a role as the swarm token context is lost outside of this playbook
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377"
      register: swarm_info
    - name: Add dummy host
      add_host:
        name: 'DUMMY_HOST'
        workerToken: '{{ swarm_info.swarm_facts.JoinTokens.Worker }}'
        managerToken: '{{ swarm_info.swarm_facts.JoinTokens.Manager }}'
        managerAddr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377"
    - name: Get info on host if it is Swarm Manager
      docker_node_info:
        self: true
      register: result
    - name: 'Label Leader Node'
      community.docker.docker_node:
        hostname: '{{ result.nodes[0].Description.Hostname }}'
        labels:
          name: '{{hostvars[inventory_hostname].name}}'

- hosts: managers
  tasks:
    # This task is not split into a role as the swarm token context is lost outside of this playbook
    - name: Add manager nodes to swarm network
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars['DUMMY_HOST']['managerToken'] }}"
        remote_addrs: ["{{ hostvars['DUMMY_HOST']['managerAddr'] }}"]
    - name: Get info on host if it is Swarm Manager
      docker_node_info:
        self: true
      register: result
    - name: 'Label Manager Node'
      community.docker.docker_node:
        hostname: '{{ result.nodes[0].Description.Hostname }}'
        labels:
          name: '{{hostvars[inventory_hostname].name}}'

- hosts: workers
  tasks:
    # This task is not split into a role as the swarm token context is lost outside of this playbook
    - name: Add worker nodes to swarm network
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars['DUMMY_HOST']['workerToken'] }}"
        remote_addrs: ["{{ hostvars['DUMMY_HOST']['managerAddr'] }}"]
