version: '3.9'

services:
  mapping-mediator-config-importer:
    image: jembi/instantohie-config-importer
    deploy:
      restart_policy:
        condition: none
    configs:
      - source: mediator-config-metadata.js
        target: /metadata.js
      - source: mediator-config-registerFacility.json
        target: /registerFacility.json
      - source: mediator-config-getFacilities.json
        target: /getFacilities.json
      - source: mediator-config-getClientByUid.json
        target: /getClientByUid.json
      - source: mediator-config-getClientByNid.json
        target: /getClientByNid.json
      - source: mediator-config-getClientByMr.json
        target: /getClientByMr.json
      - source: mediator-config-getClientDiagnosisByUid.json
        target: /getClientDiagnosisByUid.json
      - source: mediator-config-getEpisodeOfCareByUid.json
        target: /getEpisodeOfCareByUid.json
      - source: mediator-config-getHivTestingByUid.json
        target: /getHivTestingByUid.json
      - source: mediator-config-getArvTreatmentByUid.json
        target: /getArvTreatmentByUid.json
      - source: mediator-config-submitBundle.json
        target: /submitBundle.json
      - source: mediator-config-getLabOrder.json
        target: /getLabOrder.json
      - source: mediator-config-getLabOrders.json
        target: /getLabOrders.json
      - source: mediator-config-getLabOrdersNew.json
        target: /getLabOrdersNew.json
      - source: mediator-config-getLabOrdersHistory.json
        target: /getLabOrdersHistory.json
    networks:
      openhim:
    # This command will only attempt to import the config when the uptime responds with a 2xx
    command: sh -c "wait-on -t 60000 http-get://openhim-mapping-mediator:3003/uptime && node /metadata.js"

configs:
  mediator-config-metadata.js:
    file: ./metadata.js
    name: mediator-config-metadata.js-${mediator_config_metadata_js_DIGEST:?err}
    labels:
      name: fhir-training
  mediator-config-registerFacility.json:
    file: ./registerFacility.json
    name: mediator-config-registerFacility.json${mediator_config_registerFacility_json_DIGEST:?err}
    labels:
      name: fhir-training
  mediator-config-getFacilities.json:
    file: ./getFacilities.json
    name: mediator-config-getFacilities.json${mediator_config_getFacilities_json_DIGEST:?err}
    labels:
      name: fhir-training
  mediator-config-getClientByUid.json:
    file: ./getClientByUid.json
    name: mediator-config-getClientByUid.json${mediator_config_getClientByUid_json_DIGEST:?err}
    labels:
      name: fhir-training
  mediator-config-getClientByNid.json:
    file: ./getClientByNid.json
    name: mediator-config-getClientByNid.json${mediator_config_getClientByNid_json_DIGEST:?err}
    labels:
      name: fhir-training
  mediator-config-getClientByMr.json:
    file: ./getClientByMr.json
    name: mediator-config-getClientByMr.json${mediator_config_getClientByMr_json_DIGEST:?err}
    labels:
      name: fhir-training      
  mediator-config-getClientDiagnosisByUid.json:
    file: ./getClientDiagnosisByUid.json
    name: mediator-config-getClientDiagnosisByUid.json${mediator_config_getClientDiagnosisByUid_json_DIGEST:?err}
    labels:
      name: fhir-training    
  mediator-config-getEpisodeOfCareByUid.json:
    file: ./getEpisodeOfCareByUid.json
    name: mediator-config-getEpisodeOfCareByUid.json${mediator_config_getEpisodeOfCareByUid_json_DIGEST:?err}
    labels:
      name: fhir-training   
  mediator-config-getHivTestingByUid.json:
    file: ./getHivTestingByUid.json
    name: mediator-config-getHivTestingByUid.json${mediator_config_getHivTestingByUid_json_DIGEST:?err}
    labels:
      name: fhir-training         
  mediator-config-getArvTreatmentByUid.json:
    file: ./getArvTreatmentByUid.json
    name: mediator-config-getArvTreatmentByUid.json${mediator_config_getArvTreatmentByUid_json_DIGEST:?err}
    labels:
      name: fhir-training       
  mediator-config-submitBundle.json:
    file: ./submitBundle.json
    name: mediator-config-submitBundle.json${mediator_config_submitBundle_json_DIGEST:?err}
    labels:
      name: fhir-training       
  mediator-config-getLabOrder.json:
    file: ./getLabOrder.json
    name: mediator-config-getLabOrder.json${mediator_config_getLabOrder_json_DIGEST:?err}
    labels:
      name: fhir-training    
  mediator-config-getLabOrders.json:
    file: ./getLabOrders.json
    name: mediator-config-getLabOrders.json${mediator_config_getLabOrders_json_DIGEST:?err}
    labels:
      name: fhir-training    
  mediator-config-getLabOrdersNew.json:
    file: ./getLabOrdersNew.json
    name: mediator-config-getLabOrdersNew.json${mediator_config_getLabOrdersNew_json_DIGEST:?err}
    labels:
      name: fhir-training   
  mediator-config-getLabOrdersHistory.json:
    file: ./getLabOrdersHistory.json
    name: mediator-config-getLabOrdersHistory.json${mediator_config_getLabOrdersHistory_json_DIGEST:?err}
    labels:
      name: fhir-training 

networks:
  openhim:
    name: openhim_public
    external: true
